# Dependencies
markdown:         redcarpet
hightlighter:     rouge

# Permalinks
permalink:        pretty

# Setup
title:            Brayden Lopez
tagline:          I do cool things sometimes
url:              http://mrlopez.me/blog
paginate:         5
baseurl:          /blog
author:
  name:           Brayden Lopez
  url:            http://mrlopez.me
  email:          braydenjaclopez@gmail.com
sass:
  style: :compressed

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.1.0
github:
  repo:           https://github.com/headdetect/blog
