# Dependencies
markdown:         redcarpet
hightlighter:     rouge
github:           [Repository metadata]

# Permalinks
permalink:        pretty

# Setup
title:            Nothing To See
tagline:          There's nothing here worth your time..
url:              http://mrlopez.me/blog
paginate:         5
baseurl:          /blog/
author:
  name:           Brayden Lopez
  url:            http://mrlopez.me
  email:          braydenjaclopez@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/headdetect/blog
