# Dependencies
markdown:         redcarpet
hightlighter:     rouge
github:           [Repository metadata]

# Permalinks
permalink:        pretty

# Setup
title:            Brayden Lopez
tagline:          I do cool things sometimes
url:              http://mrlopez.me/blog
paginate:         5
baseurl:          /blog
author:
  name:           Brayden Lopez
  url:            http://mrlopez.me
  email:          braydenjaclopez@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/headdetect/blog
