# Dependencies
markdown:         redcarpet
hightlighter:     rouge

# Setup
title:            Brayden Lopez
tagline:          I do cool things sometimes
url:              http://mrlopez.me/blog
paginate:         5
baseurl:          /blog
author:
  name:           Brayden Lopez
  url:            http://mrlopez.me
  email:          braydenjaclopez@gmail.com
sass:
  style:          compressed

permalink:           pretty
relative_permalinks: true

github:
  repo:             https://github.com/headdetect/blog
